Adding the environment magento-cloud to be used by den env-ini command.
swiftotter/den pull request #93
Opened 2022-10-08 17:09 UTC by henriquekieckbusch

It adds the environment "magento-cloud"
So the command `den env-init <name> magento-cloud` will create a magento2's .env file, but all the services versions come from your Magento Cloud project.

2022-10-10 10:04 UTC, navarr reviewed
It looks good!  Are you willing to update it to detect Elasticsearch vs OpenSearch?

2022-10-10 10:05 UTC, henriquekieckbusch commented
Hey @navarr ! Sure, it is possible, let me update it soon.

2022-10-10 18:00 UTC, navarr approved these changes

2022-10-12 14:32 UTC, navarr requested changes
This needs to be able to detect whether or not the folder we're initializing in is a Magento Cloud project.  Right now, it does not do that successfully.  It does prompt for the Magento Cloud project and environment, but it's not entirely clear (to me) why it's doing that.

Additionally, when told to import environment variables, It generated this file:

```yaml
version: '3.5'
services:
  php-fpm:
    environment:
```

And displayed the error that "Variable not found: env:COMPOSER_AUTH".  `env:COMPOSER_AUTH` is configured on the Project level.

2022-10-16 15:24 UTC, henriquekieckbusch commented
> This needs to be able to detect whether or not the folder we're initializing in is a Magento Cloud project. Right now, it does not do that successfully. It does prompt for the Magento Cloud project and environment, but it's not entirely clear (to me) why it's doing that.
> 
> Additionally, when told to import environment variables, It generated this file:
> 
> ```yaml
> version: '3.5'
> services:
>   php-fpm:
>     environment:
> ```
> 
> And displayed the error that "Variable not found: env:COMPOSER_AUTH". `env:COMPOSER_AUTH` is configured on the Project level.

it should be right on this last commit. I'm working on a new update (to create the env.php file) but I think I will wait sometime to finish that, so maybe a new PR later.

2022-10-17 13:24 UTC, navarr commented on environments/magento-cloud/init.env.cmd
> +    read -p $'\033[32mDo you want to import Environment variables? y/n\033[0m ' resp
Can we include the `$ENVIRONMENT` variable in here?  I'd make a suggestion but I've never used read so I'm not entirely clear on the format to use.

But with text something like "Do you want to import the Environment variables from $ENVIRONMENT?"

2022-10-17 13:24 UTC, navarr commented
It's working really well!  I have a single suggestion to make some phrasing more explicit

2022-10-18 18:20 UTC, navarr approved these changes

2022-10-18 18:21 UTC, merged